### ISSUE TITLE
Integration of the new php module with SOAP WSDL

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/mobileid-helper#68]

**Comment by michellotto** [comment]
Ok, new php module with SOAP WSDL is now integrated with the mobileid-helper. You can test the application fork there:
---
http://213.221.138.11/mobileid-helper/
---

And also get the repository from there:
---
git clone https://github.com/michellotto/mobileid-helper.git
---

**Comment by FreddyKaiser** [comment]
Tested and ok
