### ISSUE TITLE
Display duration (time required to retrieve the signature response)

### ISSUE THREAD

**Issue by phaupt** [SCS-CBU-CED-IAM/mobileid-helper#71]
In case of success (green), display the duration in seconds and milliseconds (s.mmm). Example: 
`The selected Mobile ID is fully functional.`
`It took 9.831 seconds.`

**Comment by michellotto** [comment]
Ok, done, but please, provide to me the translations for texts in FR, DE and IT

**Comment by FreddyKaiser** [comment]
Tested and ok

**Comment by FreddyKaiser** [comment]
Move the start of the counter behind the profileQuery
