### ISSUE TITLE
Display the unique serial number in case of success

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/mobileid-helper#72]
In case of success (green), display the SerialNumber in the DN. Example: 
The selected Mobile ID is fully functional (Unique serial number MIDCHEGU8GSH6K83)
It took 9.831 seconds.

**Comment by FreddyKaiser** [comment]
With the new class it should easy to display this message.

**Comment by michellotto** [comment]
Ok, done, but please, provide to me the translations for texts in FR, DE and IT

**Comment by FreddyKaiser** [comment]
Tested and ok
