### ISSUE TITLE
Rubin CA 2 still in use for mobile id user certificates?

### ISSUE THREAD

**Issue by hpwaldegger** [SCS-CBU-CED-IAM/mobileid-helper#83]
The certificate bag contains both 'Swisscom Rubin CA 2' and 'Swisscom Rubin CA 3' issuing certificate. While new user certificates are issued with CA3, some legacy certificates still might be in use that were issued by CA2. Please check if Rubin CA 2 issuing CA can be removed from bag.

**Comment by phaupt** [comment]
Fixed with commit ee6d433de9294f64cba462df7f2887f1fa832b2a
